name: Compilar e implementar la aplicación de .NET Core en la aplicación web APICTVWAPA

on:
  push:
    branches:
      - Dev

env:
  AZURE_WEBAPP_NAME: APICTVWAPA
  AZURE_WEBAPP_PACKAGE_PATH: Back/WebApi/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore WebApi.csproj
        working-directory: Back/WebApi

      - name: Build
        run: dotnet build WebApi.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
        working-directory: Back/WebApi

      - name: Test
        run: dotnet test --no-build
        working-directory: Back/WebApi

      - name: Publish
        run: dotnet publish WebApi.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output publish
        working-directory: Back/WebApi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: Back/WebApi/publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: Back/WebApi/publish

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.APICTVWAPA_1842 }}
          package: Back/WebApi/publish
